require("Eoin-McMahon.options")
require("Eoin-McMahon.keymaps")
require("Eoin-McMahon.commands")

require("Eoin-McMahon.plugins")
require("Eoin-McMahon.plugins.telescope")
require("Eoin-McMahon.plugins.catppuccin")
require("Eoin-McMahon.plugins.nvimtree")
require("Eoin-McMahon.plugins.whichkey")
require("Eoin-McMahon.plugins.lsp")
require("Eoin-McMahon.plugins.cmp")
require("Eoin-McMahon.plugins.treesitter")
require("Eoin-McMahon.plugins.autopairs")
require("Eoin-McMahon.plugins.comment")

