require("Eoin-McMahon.options")
require("Eoin-McMahon.keymaps")
require("Eoin-McMahon.commands")

require("Eoin-McMahon.plugins")
require("Eoin-McMahon.plugins.telescope")
require("Eoin-McMahon.plugins.colorscheme")
require("Eoin-McMahon.plugins.nvimtree")
require("Eoin-McMahon.plugins.whichkey")
require("Eoin-McMahon.plugins.glow")
require("Eoin-McMahon.plugins.lsp")
require("Eoin-McMahon.plugins.lualine")
require("Eoin-McMahon.plugins.cmp")
require("Eoin-McMahon.plugins.mason")
require("Eoin-McMahon.plugins.treesitter")
require("Eoin-McMahon.plugins.autopairs")
require("Eoin-McMahon.plugins.comment")
require("Eoin-McMahon.plugins.bufferline")

